idf_component_register(
    SRCS 
        "src/cam_task.c"
    INCLUDE_DIRS 
        "include"
        "../../include"
    PRIV_INCLUDE_DIRS
        "${CMAKE_SOURCE_DIR}/.pio/libdeps/esp32cam/esp32-camera/driver/include"
        "${CMAKE_SOURCE_DIR}/.pio/libdeps/esp32cam/esp32-camera/conversions/include"
    REQUIRES
        esp_http_client
        esp_timer
        freertos
        driver
        error_control
)