idf_component_register(
    SRCS 
        "src/wifi_manager.c"
        "src/nvs_storage.c"
        "src/http_portal.c"
        "src/dns_server.c"
    INCLUDE_DIRS 
        "include"
        "../../include"
        "src"
    REQUIRES 
        nvs_flash 
        esp_wifi 
        esp_event 
        esp_http_server 
        lwip
)